launuage: generic
sudo: required
services: 
    - docker
before_install:
    - docker build -t ruchasp/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true ruchasp/react-test npm test -- --coverage
after_success:
    - docker build -t ruchasp/multi-client ./client
    - docker build -t ruchasp/multi-nginx ./nginx
    - docker build -t ruchasp/multi-server ./server
    - docker build -t ruchasp/multi-worker ./worker

# login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin   

# push to docker hub
    - docker push ruchasp/multi-client
    - docker push ruchasp/multi-nginx
    - docker push ruchasp/multi-server
    - docker push ruchasp/multi-worker

    